analyzer:
  errors:
    avoid_print: ignore
    camel_case_types: ignore
    constant_identifier_names: ignore
    deprecated_member_use: ignore
    file_names: ignore
    library_private_types_in_public_api: ignore
    no_leading_underscores_for_local_identifiers: ignore
    sort_child_properties_last: ignore
include: package:flutter_lints/flutter.yaml
